### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by hack-scan** [lavague-ai/LaVague#107]
![image](https://github.com/lavague-ai/LaVague/assets/36232689/3c2e5e55-ac29-42dd-aa13-19b961ade9cb)
Long time no response, my GPT key input is not a problem. My version is 3.5, can I use it?

**Comment by hack-scan** [comment]
![image](https://github.com/lavague-ai/LaVague/assets/36232689/be76cddc-d176-45ad-b14a-d25ca81a7c6e)
Error in code execution: exec() arg 1 must be a string, bytes or code object

**Comment by hack-scan** [comment]
I think it should be an interface issue. I didn't recharge the GPT, so I think there should be a free quota

**Comment by hack-scan** [comment]
I think it may be my network problem. How to add a proxy when requesting, which file is it

**Comment by hack-scan** [comment]
where is CustomLLM

**Comment by dhuynh95** [comment]
Hi there!
Sorry to see those issues. We will have a look.
@mbrunel maybe? It might be related to recent changes

**Comment by lyie28** [comment]
@hack-scan I am unable to reproduce your issue. Working fine for me.

1) One thing I noticed in your screenshot is that I don't see any instruction in the instruction box - can I check you selected an instruction, clicked on it in the instruction box and pressed enter?

2) Can you tell me your set-up? Are you running this locally? In a docker container? In a Google Colab?

3) What about the HuggingFace example? Does this work for you? https://docs.lavague.ai/en/latest/docs/integrations/hugging-face-api/

**Comment by hack-scan** [comment]
Does HuggingFace cost money? I am currently switching to the domestic AI interface and it can run normally, but it is not as powerful as GPT3.5/4.0. I would like to add a request proxy function to request the GPT interface to add a proxy, because our country is not very friendly to accessing this and VPN must be used.

**Comment by lyie28** [comment]
Hello, I understand the issue better now.

HuggingFace API is free, but from a quick search, it seems it is also not accessible from China.

In case other users are having similar issues, I will also share this article you shared with me here about using LaVague with ChatGLM: https://zhuanlan.zhihu.com/p/687945821 - note I don't understand the text but the code looks useful!

I will reply more to this issue later on

**Comment by lyie28** [comment]
Hi @hack-scan,

Sorry I never came back to this. Unfortunately, we are not really able to address specific access issues to certain APIs in-house, but of course you can use our interfaces with VPNs, or test with different APIs. I hope you will still able to use/contribute to LaVague :)
