### ISSUE TITLE
HugginFace API Google Colab not working.

### ISSUE THREAD

**Issue by 11PRiyansh** [lavague-ai/LaVague#112]
While I am trying to LogIn a website, it gives the following issues:
1. The page is not being updated after Clicking on Button( specifically Continue button for login).
2.  After clicking on the LogIn button it gives the error as shown in the screenshot.

![Screenshot 2024-04-08 232141](https://github.com/lavague-ai/LaVague/assets/160034930/d0a2f6f1-ef66-40a1-89d1-2ace5063f011)

Please suggest what is going wrong here.

**Comment by shubhamofbce** [comment]
@11PRiyansh  Can you share some debug logs or the full code here so that we can investigate and help.

**Comment by 11PRiyansh** [comment]
Thanks for the reply, but I managed to solve it. However, the page doesn't load after an action( for example: click on the log in button).
It does click on the button but the page doesn't load/change to the next page(profile).

Solution:
I have to explicitly command "wait for 1 sec" for it to load/go to the next page. Is this behavior expected? 
![Screenshot 2024-04-11 002456](https://github.com/lavague-ai/LaVague/assets/160034930/e49479d3-d31c-4e96-8a85-f1a6150de602)

**Comment by shubhamofbce** [comment]
Are you saying that the screenshot is not updating after the click? So how do you got to know that it is clicked ?
Also can you check for error or any logs ??
Can you also share which LLM you are using ??

**Comment by 11PRiyansh** [comment]
Yes, that is what I mean. 
I know because of the color of the Button before and after the click changes. (Gets darker as it usually gets after a click).
There aren't any errors as it successfully executes the command.

I am using the default LLM mentioned in Huggingface.py file: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"

**Comment by dhuynh95** [comment]
Hmm it might be because the model did not understand the request.
Can you try using GPT-3.5 or GPT4?

**Comment by 11PRiyansh** [comment]
The request is being understood and executed, as when I command "wait for 1 second" it loads the next page correctly.

**Comment by lyie28** [comment]
Hi @11PRiyansh,

Unfortunately LaVague is still very much a project in progress and not a finished project, so some instructions on certain websites will not work currently, especially when it comes to logging in. We will add a page to the docs on how to increase chances of success through prompt engineering - sometimes manually adding a delay can be a solution as you say. 

We are currently focusing all our efforts on improving AI performance and speaking with the community on how to improve results, so expect results to improve over time!

If you see any other improvements or have any specific suggestions or tips, please let us know! I'll close this in the meantime.
