### ISSUE TITLE
Add error handling ability upon generated code error

### ISSUE THREAD

**Issue by y22ma** [lavague-ai/LaVague#117]
**Is your feature request related to a problem? Please describe.**
When code gets generated and it doesn't work, we throw an error and give up. The backtrace should provide very clear direction to fix the generated code and try to take another shot at it.

**Describe the solution you'd like**
Add a error handling mechanism, where if code error is encountered, dump the error into the context and retool the code.
This is a part of langchain [out of the box](https://python.langchain.com/docs/use_cases/tool_use/tool_error_handling/#retry-with-exception), the equivalent for llamaindex would be [Retry Query Engine](https://docs.llamaindex.ai/en/stable/examples/evaluation/RetryQuery/?h=query+engine#retry-query-engine).

**Describe alternatives you've considered**
maybe robustness can be increased by providing many examples in context to steer the code gen output, but backtracking is additive.

**Comment by lyie28** [comment]
Thanks for the request. I will let @dhuynh95 and @HiImMadness reply to this as it is more their area of expertise :)

**Comment by shubhamofbce** [comment]
@y22ma This is a great suggestion and we should do this. In our case we can just use lxml to evaluate if the xpath generated is correct or not. If not correct then we can use the retry query engine to generate a different or a better xpath that evaluates to a valid element before actually executing the code.

**Comment by y22ma** [comment]
Well, 

> @y22ma This is a great suggestion and we should do this. In our case we can just use lxml to evaluate if the xpath generated is correct or not. If not correct then we can use the retry query engine to generate a different or a better xpath that evaluates to a valid element before actually executing the code.

Right that would certainly help with wrong xpath extraction. I think another class of issue is mentioned in this issue I raised https://github.com/lavague-ai/LaVague/issues/116 where the generated code included missing imports.

With retry mechanism, you will atleast give the agent a chance to correct, report telemetry and keep things going.

**Comment by lyie28** [comment]
This is now handled by an automatic retry mechanism for up to X tries (can be defined by user)
