### ISSUE TITLE
Broken link to customization guide in quickstart

### ISSUE THREAD

**Issue by vincentschen** [lavague-ai/LaVague#147]
In the [Colab](https://colab.research.google.com/github/lavague-ai/lavague/blob/main/docs/docs/get-started/quick-tour-notebook/quick-tour.ipynb): Go to quick start notebook, and click link to customization guide. Leads to 404.

![image](https://github.com/lavague-ai/LaVague/assets/5819303/a0fc15bc-b634-44fa-b7b2-f9a7df766dd0)

![image](https://github.com/lavague-ai/LaVague/assets/5819303/65eb3786-77cf-43e7-b9d5-f33adcc67e4d)

**Comment by lyie28** [comment]
Thanks, fixed now.
