### ISSUE TITLE
Add playwright_ground_truth row to BigAction/the-wave-clean

### ISSUE THREAD

**Issue by shubhamofbce** [lavague-ai/LaVague#159]
**Is your feature request related to a problem? Please describe.**
We need a playwright ground truth row in the wave clean dataset to evaluate playwright scripts. 

**Describe the solution you'd like**
I would like a row similar like selenium_ground_truth for playwright_ground_truth

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by lyie28** [comment]
@dhuynh95 @HiImMadness this one is for you guys!

**Comment by shubhamofbce** [comment]
@lyie28 I discussed this with @dhuynh95 on discord, I will be taking this up.

**Comment by shubhamofbce** [comment]
Not sure, how to contribute to dataset so just created a new sheet with playwright ground truth for all queries in the dataset
https://docs.google.com/spreadsheets/d/1xwopMgt1oE91ZdhkpiX-0gPScbOM5hyM3CvRMJr8kD0/edit?usp=sharing

**Comment by lyie28** [comment]
@shubhamofbce Should I close this one now?

**Comment by shubhamofbce** [comment]
This is still open, I have created a PR on huggingface dataset which Daniel needs to review and merge.
https://huggingface.co/datasets/BigAction/the-wave-clean/discussions/4

**Comment by dhuynh95** [comment]
@shubhamofbce My bad! We will switch towards just providing the full XPath so compatibility becomes easy.
I am unsure we will maintain code inside the datasets

**Comment by lyie28** [comment]
Oki, I guess I will close this with the switch to the full XPath, but ping us on Discord if you want to discuss this further @shubhamofbce
