### ISSUE TITLE
Avoid cleaning Input attributes from html

### ISSUE THREAD

**Issue by shubhamofbce** [lavague-ai/LaVague#161]
**Describe the bug**
We need to avoid cleaning input attributes like placeholder, type and all. They are important for the agent.

**To Reproduce**
Add a query to search any input by placeholder, action engine fails as the input attribute was cleaned.

**Expected behavior**
Input attributes must not be cleaned
```python
input_attributes = ["accept", "alt", "checked", "disabled", "height", "max", "maxlength", "min",
                    "multiple", "pattern", "placeholder", "readonly", "required", "size", "src",
                    "step", "type", "value", "width"]
```

**Screenshots**
NA

**Comment by lyie28** [comment]
@shubhamofbce @mbrunel - should I close this? Seems like this was solved by changes to the retriever?

**Comment by shubhamofbce** [comment]
@lyie28 Yes you can.
