### ISSUE TITLE
【main branch】The file name with special char block branch check out

### ISSUE THREAD

**Issue by gedayin-pki** [lavague-ai/LaVague#163]
**Describe the bug**
The file name with special char block branch check out

**To Reproduce**

**Expected behavior**
normal check out

**Screenshots**
![image](https://github.com/lavague-ai/LaVague/assets/86957985/76c07e97-7454-4914-adff-f2cc34af78c6)
![image](https://github.com/lavague-ai/LaVague/assets/86957985/7b9981d2-aad5-4dc5-b454-03190f626e6f)

**Comment by dhuynh95** [comment]
Thanks for pointing that out!
Could you open a PR? Sorry, I am looking at a lot of things and it might take me more time than you to find where to change stuff

**Comment by lyie28** [comment]
Thanks for this. Have fixed the filename now @gedayin-pki
