### ISSUE TITLE
Return error when running setup script

### ISSUE THREAD

**Issue by alexsiu398** [lavague-ai/LaVague#167]
**Describe the bug**
Setup script return error and lavague command is not found

**To Reproduce**
1. wget https://raw.githubusercontent.com/lavague-ai/LaVague/main/setup.sh
2. sudo bash setup.sh
Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///~LaVague/LaVague has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

**Expected behavior**
No error is returned and lavague command can be run

**Comment by lyie28** [comment]
Hi @alexsiu398 - we install the package in editable mode which requires setuptools v62.0.0 or newer.

- You can check your version with: `pip show setuptools`
- You can update it with: `pip install --upgrade setuptools`
- You may also need to upgrade pip: `pip install --upgrade pip`

If any problems persist, you can just modify the setup.sh and remove the editable mode -e argument from pip install -e LaVague - this is only necessary for modifying and testing changes you make to the files locally so it's not necessary if you just want to run lavague without making local changes!
