### ISSUE TITLE
Integrate vision

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#17]

**Comment by badreddineFarah** [comment]
Hi, i want to contribute help in this task but, how do you see the integration of vision, but I don't fully understand how do you ant to do this  is it  sending snapshots of the web page ?

**Comment by dhuynh95** [comment]
Discussed with @badreddineFarah

The idea is : 
Today we take low level instructions like "Select X, do Y".For the retriever to work well, we have to be quite specific but it's annyoing to write
The goal is to use vision model to provide mid level instructions, like "this form with name "Daniel", phone "+123", and age is 16.", a screenshot of the current page, and have the vision model generate the low level instructions
Example I did is I gave: 
- This image
![image](https://github.com/lavague-ai/LaVague/assets/36925557/6697e4f9-287e-4f7d-983f-ce0d0deec9c5)
- This prompt " fill this form with name "Daniel", phone "+123", and age is 16."

And it generated the instructions: 
- Select the input with placeholder 'This is where you fill name', then type 'Daniel'
- Select the input with placeholder 'This is where you fill your phone number', then type '+123'
- Select the radio button next to the age '18-24', then click on it

We will first start by creating a dataset of inputs (screenshot, mid level instructions) to produce (low level instructions).

The dataset is being collected by @badreddineFarah, and we will test it soon with LaVague to see how the low level instructions are properly executed!
