### ISSUE TITLE
When using deepseek coder, cannot import name 'GEMMA_PROMPT' from 'lavague.prompts'

### ISSUE THREAD

**Issue by alexsiu398** [lavague-ai/LaVague#180]
**Describe the bug**
from lavague.prompts import GEMMA_PROMPT
ImportError: cannot import name 'GEMMA_PROMPT' from 'lavague.prompts'

**To Reproduce**
1. lavague -i examples/instructions/huggingface.yaml -c xamples/configurations/local/deepseek-coder.py launch
2. See error ImportError: cannot import name 'GEMMA_PROMPT' from 'lavague.prompts'

**Expected behavior**
I found out that deepseek-coder.py does not contains GEMMA_PROMPT but it contains SELENIUM_GEMMA_PROMPT

**Comment by lyie28** [comment]
Thanks @alexsiu398 - I hadn't spotted this update in the codebase. I have updated the config file on main now to use the SELENIUM_GEMMA_PROMPT
