### ISSUE TITLE
Request for Enhancing Agent Robustness Against Bot Detection

### ISSUE THREAD

**Issue by Samit33** [lavague-ai/LaVague#2]
It hasn't been effective on most of the sites I've attempted to use it on, as it's often identified as a bot. Are there any plans to enhance the agent's resilience against such detections?

**Comment by dhuynh95** [comment]
This I cannot help you with as those are legitimate defenses.
I can only tell you that I noticed that using Windows reduced the likelihood of such defenses being triggered.

**Comment by lyie28** [comment]
Hey @Samit33, 

This is not an area we are focusing on for now as we are busy working on a lot of other things, but we'd be very interested in any community developments on this.

You may be interested in this issue on creating a LaVague browser extension which we believe would reduce scrutiny of bot activity: https://github.com/lavague-ai/LaVague/issues/7
