### ISSUE TITLE
Initial setup code missing in gradio demo full code section

### ISSUE THREAD

**Issue by shubhamofbce** [lavague-ai/LaVague#202]
**Describe the bug**
When you hit enter with an url, The full code and generated code field should ideally have all the code to setup the driver and goto url code, but it remains empty as you can see in the screenshot.
<img width="1220" alt="image" src="https://github.com/lavague-ai/LaVague/assets/45156638/a4b4bfdb-a3b6-4755-963c-5160d3809e92">
Also when you enter the 1st instruction, the full code just has the code for current instruction ideally it should have the code for setup, goto url and the current instruction related code.
<img width="389" alt="image" src="https://github.com/lavague-ai/LaVague/assets/45156638/3b21b8e0-5b66-4317-ab41-e48d604f2ce8">

**To Reproduce**
1. Go to the gradio demo and hit enter with a valid url, you will see the generated code and full code fields empty.
2. Add a instruction and hit enter, you will see the generated and full code has only the code for current instruction.

**Expected behavior**
I want the full code field to have the code for driver initialisation and also goto instruction like we have in the build command.
I want it to look like this, when you hit enter for the first time.
<img width="423" alt="image" src="https://github.com/lavague-ai/LaVague/assets/45156638/f30a607a-fd8b-457f-9329-a2e39200a6eb">
And I want the full code and generated code to look like this for next instructions
<img width="416" alt="image" src="https://github.com/lavague-ai/LaVague/assets/45156638/cc8b445f-2af5-41f8-83e6-d50b592d6b12">

**Screenshots**
Added already

**Comment by shubhamofbce** [comment]
@mbrunel I have fixed this on my local, Can you just confirm if this is a valid issue or this is expected behaviour. If you think it is a bug/issue then I will create the PR for the fix.

**Comment by lyie28** [comment]
Hi @shubhamofbce, 

I half agree with you on this one: I think the full code should include the boilerplate code (driver set up code) but I don't think it should be in the generated code - as it is not generated by the LAM - which for me is the idea of the the generated code block.

**Comment by shubhamofbce** [comment]
@lyie28 You have a valid point so we can close the isssue.
