### ISSUE TITLE
Cookie accepting is an issue

### ISSUE THREAD

**Issue by saffie91** [lavague-ai/LaVague#203]
**Describe the bug**
When I go to any website that uses cookies, the assistant cant click accept all. This makes websites such as youtube unusable.

**To Reproduce**
1. Go to youtube.com and the 'accept all' button that pops up to use it is not pressable.

**Expected behavior**
I would like it if the demo didnt get locked out with the cookie screen in certain websites. Any sort of auto accept would be great, but at least it should be able to accept it with a prompt if not.

**Screenshots**

![123124](https://github.com/lavague-ai/LaVague/assets/56364750/3af028f5-3c79-4e59-a300-109c55a83fce)

**Comment by dhuynh95** [comment]
Hi @saffie91!
Thanks for pointing that out.
This would be a bit heavy to implement.
I think one solution would be to create a stateful session, for instance using developer mode with Selenium or Playwright, accept the cookies once for all, and then connect to it using LaVague.

I can show you how to do it if interested

**Comment by saffie91** [comment]
Yes I would like it if you showed how. I'm sure it would help a lot of people to update this in general. 


I tried running the default selenium session with my logged in Google profile but it did not work. Although I know that's the function being called in lavague launch I have no idea why, so would be happy for the help.

**Comment by lyie28** [comment]
@saffie91 - the project has changed greatly since we last spoke but I did finally add some docs on plugging in an existing chrome session:

https://docs.lavague.ai/en/latest/docs/learn/browser-drivers/#plugging-in-an-existing-browser-session_1

If you do test it out, please let me know if it works for you :)

**Comment by lyie28** [comment]
@saffie91 in fact either strategy mentioned now in the quick tour for logins are relevant to cookie accepting too.  You could also enforce a pause in your code and manually accept the cookie at this point: See instructions here: https://docs.lavague.ai/en/latest/docs/get-started/quick-tour/#manual-login
