### ISSUE TITLE
Error when running google colab

### ISSUE THREAD

**Issue by joostgrunwald** [lavague-ai/LaVague#24]
**Describe the bug**
When simply running all fields one for one in the google colab I get the following:

NoSuchDriverException                     Traceback (most recent call last)
[<ipython-input-6-d31e5fb12b1f>](https://localhost:8080/#) in <cell line: 40>()
     38 
     39 # Choose Chrome Browser
---> 40 driver = webdriver.Chrome(service=webdriver_service, options=chrome_options)
     41 
     42 # action_engine = ActionEngine(llm, embedder)

2 frames
[/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/driver_finder.py](https://localhost:8080/#) in get_path(service, options)
     42 
     43         if path is None or not Path(path).is_file():
---> 44             raise NoSuchDriverException(f"Unable to locate or obtain driver for {options.capabilities['browserName']}")
     45 
     46         return path

NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

I was able to fix it by removing the service from the initialization so instead of # Choose Chrome Browser
driver = webdriver.Chrome(service=webdriver_service, options=chrome_options) I did driver = webdriver.Chrome( options=chrome_options)

**Comment by xick66** [comment]
import os.path
homedir = os.path.expanduser("~")
chrome_options.binary_location = f"/content/chrome-linux64/chrome"
webdriver_service = Service(f"/content/chromedriver-linux64/chromedriver")
print('hii',webdriver_service)
print('hello',chrome_options.binary_location)

use this path

**Comment by dhuynh95** [comment]
Sorry guys my bad for that. It should be fixed with the recent [commit](https://github.com/lavague-ai/LaVague/commit/fa3d80071c2fe6a46dfb2f5d11b852c6abca4c56).
