### ISSUE TITLE
Log agent flow / experiments

### ISSUE THREAD

**Issue by gaspardmvr** [lavague-ai/LaVague#241]
It would be helpful to log the flow that an agent has taken in order to review where it's reasoning/thoughts and actions could be improved and if changing the world model helps with that.

In agent.run make a "log" argument optional (boolean). Then create a log folder where to store the different runs. Include the parameters for the run (prompt, site/page, world model, LLM (system fingerprint)) and the output (thoughts, actions, chosen elements, screenshots (optionally the HTML?)) per step.

Extra options, thoughts:
- succesful completion or not
- number of steps to complete task
- debug/improvement suggestions
- sort runs per task to incrementally improve agent performance per experiment

**Comment by dhuynh95** [comment]
Hi @gaspardmvr!
That's a very good point. @JoFrost is actually working on that.
We will provide this feature soon, so stay tuned

**Comment by lyie28** [comment]
This feature is now live by the way - we'll document it in Learn>Debugging guide on our docs ASAP but basically you can get a Pandas dataframe with local log info by running:

```python
df = agent.logger.return_pandas()
```

**Comment by lyie28** [comment]
The logger guide is actually here: https://docs.lavague.ai/en/latest/docs/learn/local-log/
