### ISSUE TITLE
Handle new tabs

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#242]
![invoice_dl_lavague](https://github.com/lavague-ai/LaVague/assets/22163205/08372372-8472-48f2-a436-a12961065456)

I was trying to download my OpenAI invoices using LaVague with objective "Download all my invoices" starting from url "https://platform.openai.com/settings/organization/billing/overview". I bind the driver to Chrome in debug mode in order to avoid bot protections. 

Issue: 
- When LaVague clicks a link that opens a new tab, it always switches back to the first tab. 
- LaVague should be able to handle new tabs and proceed from there.

**Comment by dhuynh95** [comment]
If someone is interested in taking that one we would be happy to receive help :)
