### ISSUE TITLE
Export option code/actions generated by agent

### ISSUE THREAD

**Issue by FaizRasool** [lavague-ai/LaVague#253]
I intend to use this tool for testing a web application. The idea is that it records actions generated for Selenium and saves them as a new code file. This allows users to run / modify the code multiple times for verification purposes without paying open ai and lot more repeatable.

So this act as first step for the QA tester to write automation script.

**Comment by lyie28** [comment]
@dhuynh95 @FaizRasool We have been talking about trying to add export options and we will probably make these `help-wanted` issues.  I think a wrapper around exporting code would be a great start. Then hopefully we can add export integrations for things for pytest, fastAPI, etc.

If you're interested in working on anything like this, let us know @FaizRasool :)
