### ISSUE TITLE
Offline model support

### ISSUE THREAD

**Issue by Formartha** [lavague-ai/LaVague#255]
Hello,

To support information protection, I suggest to try to have a local GPT model helping parsing a UI page. For that, using LLAMA 3 could be good enough.

I can try to work around it, but I suggest first to speak about it.
A project Iv'e used to load pre-defined model is: https://github.com/Formartha/ai1899

I would appreciate your inputs.

**Comment by lyie28** [comment]
Hi @Formartha - LaVague is made to be customizable so you can swap out any of our default models for any LlamaIndex compatible models you want, so you can use local models.

There is some information on how to do this here: [](https://docs.lavague.ai/en/latest/docs/get-started/customization/)

Does that help? Feel free to share your local config on our Discord!

**Comment by lyie28** [comment]
Hi @Formartha,

Just to add an example - you could try with any HF LLM - performance will vary but feel free to test different models and let us know how you get on:

```python
from lavague.drivers.selenium import SeleniumDriver
from lavague.core import ActionEngine, WorldModel
from lavague.core.agents import WebAgent
from lavague.core.logger import AgentLogger
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.huggingface import HuggingFaceLLM

driver = SeleniumDriver(headless=True)

llm = HuggingFaceLLM(model_name="deepseek-ai/deepseek-coder-6.7b-instruct")
embedding = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)

action_engine = ActionEngine(driver=driver, llm=llm, embedding=embedding)
world_model = WorldModel()

agent = WebAgent(world_model, action_engine)

agent.get("https://huggingface.co/")
agent.run("what is the top model")
```

Here I use a local embedder and LLM. I still use OpenAI for the multi-modal LLM used by the World Model though because I am not aware of an open source alternative working well at the moment - we're working on this!

**Comment by lyie28** [comment]
Will close for now as no new activity on this one for a while. Feel free to re-open or ping us if you want to discuss this further @Formartha
