### ISSUE TITLE
Support with e2b.dev sandboxed environments

### ISSUE THREAD

**Issue by kecyf** [lavague-ai/LaVague#265]
Hey!

Just opening the idea here as you advise to run agents in sandboxed envs...

-->
Integrate LaVague with e2b.dev sandboxed environments (as they're basically dedicated to this vp) to enhance the capabilities of LaVague by allowing AI Web Agents developed with the framework to execute code securely in isolated environments.

**Comment by lyie28** [comment]
It's a nice idea to have an integration for a sandboxed env. @dhuynh95 what do you think? It could be something to open as a help-wanted issue for community contributors?

**Comment by lyie28** [comment]
Hey @kecyf, we have instead tackled the security aspect by integrating safeguards around which actions can be run. The agent can now only run some pre-defined actions.
