### ISSUE TITLE
Groq Integration

### ISSUE THREAD

**Issue by Vasanthengineer4949** [lavague-ai/LaVague#269]
Couldnt find how to use groq llm. If support is available please provide a sample document on how to use

**Comment by lyie28** [comment]
Hi @Vasanthengineer4949,

Something like this should work. You just need to have your `GROQ_API_KEY` set as an env variable in your working environment and have `llama_index.llms.groq` installed.

```
from llama_index.llms.groq import Groq
from lavague.core import WorldModel, ActionEngine, PythonEngine
from lavague.core.agents import WebAgent
from lavague.contexts.openai import OpenaiContext
from lavague.drivers.selenium import SeleniumDriver

# Initialize the default context
context = OpenaiContext()

# Customize the LLM
context.llm = Groq(model="mixtral-8x7b-32768")

# Initialize the Selenium driver
selenium_driver = SeleniumDriver()

# Initialize a WorldModel passing it the custom context
world_model = WorldModel.from_context(context)

# Initialize an ActionEngine with the customized context
action_engine = ActionEngine.from_context(context, selenium_driver)

# Create your agent
agent = WebAgent(world_model, action_engine, PythonEngine())

agent.get("https://huggingface.co/docs")
agent.run("Go on the quicktour of PEFT")
```

**Comment by Vasanthengineer4949** [comment]
It still requires OpenAI API Key?

**Comment by AliasHolmes** [comment]
I also tried with Litellm but no luck. LaVague doesn't support anything other than OpenAI.

**Comment by lyie28** [comment]
Hi @Vasanthengineer4949,

Yes, there are three models used by our agents: 
- the `llm` LLM (used by the ActionEngine to convert instructions into code)
- the `embedding` model (used by the ActionEngine as part of RAG)
- the `mm_llm` multi-modal LLM (used by the World Model to create step-by-step instructions based on your objective and the visual and textual state of the webpage)

They ALL by default used OpenAI models as this achieves the best performance.

In the code I sent you I only replaced the LLM, so if you wanted to not rely on OpenAI at all - you'd need to change all three elements.

However, we haven't benchmarked the performance with various open and closed source models yet - we hope to do this in the next few weeks - but often the performance appears not to be good enough with various open source models so far, especially for the multi-modal llm.

Embedding seems to work well with local embedding with a HF embedder like `BAAI/bge` though.

**Comment by lyie28** [comment]
@AliasHolmes - generally, you should be able to replace any of the three elements I mention before with any `llama_index.llms` LLM, `llama_index.embeddings` embedding model or any llama_index.multi_modal_llms - provided the LLMs have a big enough context window.

Whether the performance is currently acceptable with them is another question though - we will release more documentation soon on how to debug performance issues.

We are still at an early stage of the project so we hope to get more resources out asap including benchmarks of performance with different models so you have an idea of what will work well or not.

**Comment by AliasHolmes** [comment]
We will definitely wait for native GROQ API support.

**Comment by Vasanthengineer4949** [comment]
> Hi @Vasanthengineer4949,
> 
> Yes, there are three models used by our agents:
> 
> * the `llm` LLM (used by the ActionEngine to convert instructions into code)
> * the `embedding` model (used by the ActionEngine as part of RAG)
> * the `mm_llm` multi-modal LLM (used by the World Model to create step-by-step instructions based on your objective and the visual and textual state of the webpage)
> 
> They ALL by default used OpenAI models as this achieves the best performance.
> 
> In the code I sent you I only replaced the LLM, so if you wanted to not rely on OpenAI at all - you'd need to change all three elements.
> 
> However, we haven't benchmarked the performance with various open and closed source models yet - we hope to do this in the next few weeks - but often the performance appears not to be good enough with various open source models so far, especially for the multi-modal llm.
> 
> Embedding seems to work well with local embedding with a HF embedder like `BAAI/bge` though.


Can you please say how to add embedder locally and vlm too?

**Comment by dhuynh95** [comment]
@AliasHolmes @Vasanthengineer4949 
I tweaked the prompt template to be shorter, and also reduced the number of retrieved HTML chunks, and made Grok with Llama 8b work! 

```python
from lavague.drivers.selenium import SeleniumDriver
from lavague.core import ActionEngine, WorldModel
from lavague.core.agents import WebAgent
from lavague.core.navigation import NavigationEngine
from lavague.core.retrievers import OpsmSplitRetriever
from lavague.contexts.openai import OpenaiContext
from llama_index.llms.groq import Groq

retriever = OpsmSplitRetriever(top_k=2)

selenium_driver = SeleniumDriver(headless=True)
context = OpenaiContext()
llm = Groq(model="llama3-8b-8192")
embed_model = context.embedding

navigation_engine = NavigationEngine(driver=selenium_driver, retriever=retriever)
navigation_engine.llm = llm
navigation_engine.embedding = embed_model

action_engine = ActionEngine(selenium_driver, navigation_engine=navigation_engine, llm=llm, embedding=embed_model)
world_model = WorldModel()

agent = WebAgent(world_model, action_engine, n_steps=5)

agent.get("https://huggingface.co/docs")
agent.run("Go on the quicktour of PEFT", display=True)
```

It does run pretty fast now :)

Will prepare PR to provide an option to purely local navigation engine with embedding and LLM locally

**Comment by AliasHolmes** [comment]
Thanks for sharing buddy @dhuynh95

**Comment by lyie28** [comment]
The thing to bear in mind is that here we substitute only the LLM. We can substitute the embedding (I'll share that example with you soon) - but we leave the mm_llm as the GPT4-o with OpenAI because the performance is not good enough otherwise. We are working on an open-source solution for the mm_llm but for now, we have not found a good enough alternative @Vasanthengineer4949 @AliasHolmes

**Comment by AliasHolmes** [comment]
@lyie28 Did you try llava-llama? here's the link [](https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf)

**Comment by lyie28** [comment]
Let's check with @dhuynh95 as he's been testing some open-source stuff recently?

Interesting visual for LLM performance after testing by the way:

![image](https://github.com/lavague-ai/LaVague/assets/52970539/0832f000-2ac2-4c54-a778-ecc2e72f7b38)

Also, if there are things we haven't tested and you have time and are able to test them - do let us know if you find any models that are performing well!

**Comment by lyie28** [comment]
We have an open issue about open source help-wanted issue on vision models here too: https://github.com/lavague-ai/LaVague/issues/272

**Comment by lyie28** [comment]
We have a new `eval` module now too which makes it easier to test and assess the performance of LaVague with different models: https://docs.lavague.ai/en/latest/docs/learn/evaluation/

Will close this one as no new activity for a while but would recommend you join us on Discord if you want to discuss using LaVague with open source models further: https://discord.gg/8PcrX3u8
