### ISSUE TITLE
Add in the logger token consumption 

### ISSUE THREAD

**Issue by dhuynh95** [lavague-ai/LaVague#273]
We now have a logger with `df = agent.logger.return_pandas()`

It does not log yet the amount of tokens consumed by the `llm` and `mm_llm`. It could be good to record these for people to reduce their consumption on OpenAI ^^

I guess we could use [observability tooling from llama_index](https://docs.llamaindex.ai/en/stable/module_guides/observability/) as we are leveraging their wrappers.

**Comment by lyie28** [comment]
Duplicated by issue #355 : https://github.com/lavague-ai/LaVague/issues/355
