### ISSUE TITLE
Save logs locally

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#288]
Right now, you can only obtain logs at runtime with `agent.logger.return_pandas()`. For convenience we should have local copies of logs every time LaVague runs.

Feature: 
- V1: save logs locally, only after the agent has finished running. A csv perhaps ?
- V2: write logs at each step to get logs even in case of crashes.

**Comment by mattanapol** [comment]
@paulpalmieri Please review PR #328 and feel free to leave any suggestion.
