### ISSUE TITLE
The gradio-demo.ipynb does not work, also it does not show what is the error.

### ISSUE THREAD

**Issue by Samit33** [lavague-ai/LaVague#29]
I tried running the gradio demo in colab. It is not working. Just shows an error message without telling what is causing the error.
![error_part1](https://github.com/lavague-ai/LaVague/assets/28060127/d17d8c70-b25b-4cd9-9ec9-8f64aff8bca4)
![error_part2](https://github.com/lavague-ai/LaVague/assets/28060127/765fbdf5-ae78-40d6-95e6-c9e2961b202f)

**Comment by dhuynh95** [comment]
I saw that too I am sorry! We are investigating, I think it's a dependency issue.

**Comment by shubhamofbce** [comment]
@Samit33 By default debug is false in notebook so you will not see gradio error logs, try turning it true as shown in this ss. Let us know if you can see some logs for your error after that.

<img width="426" alt="image" src="https://github.com/lavague-ai/LaVague/assets/45156638/fa34794b-0975-4f1c-84ed-edcd442d08b1">

**Comment by dhuynh95** [comment]
We found the issue, there was a problem with llama-index streaming that caused it to return None.

We provided a quick fix by removing streaming. Colab is working again. Opening an issue to fix streaming.

**Comment by deepbeepmeep** [comment]
Hi,
I would be grateful if you could provide a fix also for the local LLM since it is broken as well

**Comment by dhuynh95** [comment]
@deepbeepmeep I changed the way to extract output which made local models fail. 

It should be fixed with the next [PR](https://github.com/lavague-ai/LaVague/pull/31)

**Comment by dhuynh95** [comment]
@deepbeepmeep Fixed. It should work for you now
