### ISSUE TITLE
Missing dependencies in Installation 

### ISSUE THREAD

**Issue by 11PRiyansh** [lavague-ai/LaVague#290]
command:
pip install lavague
python agent_example.py
error: 
No module found: lavague-core
After manually installing lavague-core and other dependencies I am getting subtrace error and the code crashes.
(After somehow solving the dependency issues I also got Invalid API key, even after the key was valid).

Please let me know if I am missing anything.

Thank You.

**Comment by lyie28** [comment]
Hi @11PRiyansh,

What environment/ set-up do you have? I just tested in a new Colab environment and can't reproduce the bugs so it should be something related to your particular env/set-up.

Can you share your errors/trace please?

**Comment by 11PRiyansh** [comment]
I am on Windows and am also experiencing the same behavior on wsl.

After installations,
![Screenshot 2024-06-04 172933](https://github.com/lavague-ai/LaVague/assets/160034930/41be5d06-2644-4331-8e1f-a57f487460d4)
 I get this error:
