### ISSUE TITLE
Getting UI display for other links.

### ISSUE THREAD

**Issue by 11PRiyansh** [lavague-ai/LaVague#291]
I am using Colab notebook, It works great with huggingface website with the UI display.
But with a different website it runs in headless manner. Is there a way to get the UI similar to huggingface link?
Is this expected behavior?

![image](https://github.com/lavague-ai/LaVague/assets/160034930/e7192913-54fc-4c2e-8cbd-0e585851ec95)

**Comment by lyie28** [comment]
@11PRiyansh In Google Colab, you can add the `display=True` argument to your `agent.run()` method. It still runs in headless but it will display screenshots so you can see what is going on!
