### ISSUE TITLE
Wait until page load to take screenshot

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#296]
On certain sites, LaVague takes a screenshot too early on a page that hasn't finished loading. LaVague should wait until the page has fully loaded before taking a screenshot.

**Comment by jashuajoy** [comment]
Could you pls provide url for a site this is happening?

**Comment by paulpalmieri** [comment]
Hey @jashuajoy, check out this site: https://speedmonitor.io/topsites 

I guess https://cnn.com would be the first to try haha

**Comment by paulpalmieri** [comment]
I've actually had trouble replicating this behavior, I'll do some more tests next week. Let me know if you're able to replicate :)
