### ISSUE TITLE
Better handling of cookies and logins

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#297]
Users would like LaVague to handle cookies and logins. How could we manage that better ?

While I'll write more docs to show how one can run LaVague from a personal Chrome session (already logged in to sites, cookies only need to be accepted once). 

However, bot all agents can be run from personal chrome user session and we should think about a more systematic way of handling cookies and login.

**Comment by lyie28** [comment]
Hi! Why do you say not all agents can be run from personal chrome user sessions? What kind of use case do you have in mind when you say that? The other way around it currently is to enforce a pause to do manual log ins, or like a manual accept cookie or whatever, and then have your program continue after your manual intervention?

I don't know, maybe what would be good is if LaVague had mode where it could recognize there is a login or cookies box and ask the user to manually do it and then carry on with the following run commands when that is done? @dhuynh95 - feature idea? Could define it and leave it as a help-wanted task for example?
