### ISSUE TITLE
Streaming broken

### ISSUE THREAD

**Issue by dhuynh95** [lavague-ai/LaVague#30]
#29 highlighted some recent issue with llama-index streaming not working anymore.
Have to fix it

**Comment by deepbeepmeep** [comment]
Hi,
I would be grateful if you could provide a fix also for the local LLM since it is broken as well

**Comment by lyie28** [comment]
@deepbeepmeep, we are releasing some updates to the local code this week and some documentation so I think this will fix any issues.

I'll close this issue now because streaming is fixed but please submit a bug report if you are still having issues at the end of the week with local inference
