### ISSUE TITLE
Qa_automation.py gives unknown model error for gpt4o

### ISSUE THREAD

**Issue by 11PRiyansh** [lavague-ai/LaVague#308]
![image](https://github.com/lavague-ai/LaVague/assets/160034930/cf32aefa-c791-46c1-852e-d1e7f286375a)

I am unable to run the QA _automation.py as the llamaindex does not have gpt 4o but the script loads that mode. 
I get the same error even after changing the model in the script to 4 or 3.5.

Is this a dependency/version issue? Because I checked all the versions from peotry.lock, it macthes.
Kindly advice.

**Comment by paulpalmieri** [comment]
@11PRiyansh Hello, let me try to help you!

- Were you able to run a normal LaVague agent (not from this qa_automation script) ? 
- Do you have the latest llama index version ? You can try doing `pip install --upgrade llama-index` and re-run the script

The script in itself doesn't use llama index but LaVague does, I'm thinking this could very well be a version issue. 

Let me know if that helps.

**Comment by 11PRiyansh** [comment]
Thanks, I did that, it worked. It went forward from the error and now it gives:
![image](https://github.com/lavague-ai/LaVague/assets/160034930/bfb9ffc9-e1ac-4046-b95c-eb723ffde4c8)

Is this a version issue aswell?
Thanks again.

**Comment by paulpalmieri** [comment]
It works on my side so I think it's also a version issue. Try updating LaVague by doing `pip install --upgrade lavague`

Let me know how it goes!

**Comment by paulpalmieri** [comment]
Hey @11PRiyansh, did you fix your issue ?

**Comment by 11PRiyansh** [comment]
Hey Yes, Thank you that did the job. My bad.

**Comment by paulpalmieri** [comment]
With pleasure, let me know what you think of the script and how it could be improved :)
