### ISSUE TITLE
Screenshot name is too long, raises an OS error and crashes LaVague

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#338]
**Describe the bug**
Screenshots seem to be saved according to the URL of the current page. URLs can be very long and the OS will raise an error for a filename that is too long. This crashes LaVague. 

**To Reproduce**
Launch LaVague to buy something on Amazon, end up on a product page, wait for LaVague to take a screenshot. 

Example Query: 
`Achete des croquetes Ultima Croquettes pour Chat Stérilisé Adult avec du Poulet - Pack 8 x 1,5kg sur amazon`

Error: 
```
OSError: [Errno 63] File name too long: 'screenshots/https_www.amazon.fr_Ultima-Croquettes-St%C3%A9rilis%C3%A9-Adult-Poulet_dp_B09ZPHQPX5_ref=sr_1_3?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=8O633LOQA169&dib=eyJ2IjoiMSJ9.Q_QDhJ_-tzvTKA8OKFNgrcRdXCTsKMih0TiBFsNPUD2lfLwqo8vWtGZpsdhjjGbV2msYNcBr1Oa0lzeD-ouuVZdl2pmBcBQLHJySniVKNk5h28cFr4aNCQV3rU-xa6EeEUOQ5gWOrhAS0vFRD5yYilzpnlNbGTQ0KyWOOgVULMtHKnwvdRfqQ0KCq6rQueakCLeMF6Z3-mNznHnUnH0_0OLWScqb2XcnAwSrardAymwYq9JppJdmHpc6h-c29aUsS-JFipEq_J_CNPM5Pdjb_EiD-fNTOOQP4FEStcLRNbI.gz6ueoc9cOsnWCSLL61RGJZ5MgXIuN0mWxaieDNQyvg&dib_tag=se&keywords=Ultima%2BCroquettes%2Bpour%2BChat%2BSt%C3%A9rilis%C3%A9%2BAdult%2Bavec%2Bdu%2BPoulet%2B-%2BPack%2B8%2Bx%2B1%2C5kg&qid=1718194529&sprefix=u%2Caps%2C80&sr=8-3&th=1'
```

**Expected behavior**
LaVague shouldn't fail because it can't save a screenshot to the OS.

**Comment by lyie28** [comment]
Do you want to take this @JoFrost or should I do a PR?

**Comment by paulpalmieri** [comment]
@JoFrost @lyie28 Matthias mentionned doing a hash of the URL :)

**Comment by JoFrost** [comment]
I was thinking about that solution actually. I'm doing it right now. @paulpalmieri
