### ISSUE TITLE
Logs not saved on interruption

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#339]
**Describe the bug**
Currently, logs are only saved when agent.run() completes. This applies to both saving logs as a local file using LocalLogger and as a pandas DataFrame using the default logger.

**To Reproduce**

1.	Using pandas:
	•	Run an agent in a notebook for a few steps.
	•	Stop it.
	•	Try to retrieve logs with agent.logger.return_pandas().
	•	The logs will be empty.
2.	Using LocalLogger:
	•	Instantiate LocalLogger and pass it to the agent.
	•	Run the agent.
	•	Stop it using a keyboard interrupt.
	•	The logs will be empty.

**Expected behavior**
To ensure we have usable logs even if the agent crashes, the logging mechanism should be modified to append logs continuously throughout the agent’s run.

**Comment by JoFrost** [comment]
I'll take care of this

**Comment by dhuynh95** [comment]
@JoFrost I think you have it in mind, but just catching Keyboard interrupt should do the trick

**Comment by paulpalmieri** [comment]
Hey @JoFrost, have you made progress on this ? I think it's pretty important to have that so we can provide detailed logs in all of our future issues to help you pinpoint the problems.

**Comment by JoFrost** [comment]
@paulpalmieri Yep. I'll merge the PR #366 in a bit.
