### ISSUE TITLE
ActionEngine.from_context() missing some options

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#346]
The ActionEngine.from_context() method should have all the options as the default constructor. 
 
 The missing options need to be added to the from_context() method.

**Comment by aaronted009** [comment]
Hello, if I'm getting it right, you want the `ActionEngine.from_context()` to have all parameters as `ActionEngine` default constructor. Is that right?

**Comment by lyie28** [comment]
Yes, exactly. But, actually, it will not need the LLM or embedding, since they are defined in the context.

But it is lacking:

time_between_actions: float = 1.5,
n_attempts: int = 5,
logger: AgentLogger = None,

**Comment by aaronted009** [comment]
Alright, I can do the update if that's ok

**Comment by lyie28** [comment]
Great! Will mark is as assigned :)

**Comment by aaronted009** [comment]
Hello @lyie28, I made a PR. Do you mind taking a look?
