### ISSUE TITLE
Leverage the accessibility tree for the Navigation Engine

### ISSUE THREAD

**Issue by dhuynh95** [lavague-ai/LaVague#348]
Someone rightly pointed yesterday that we could use the accessibility tree during the webinar.
Got to say I heard of it but haven't checked.

I think this is something where the community could help.

We will draw the details of implementation with @mbrunel and @HiImMadness and share the steps to implement it here

**Comment by adeprez** [comment]
In the same vein we can use the `for` attribute to enrich element context even when `aria-label` is absent.

```html
<label for="abc">Search</label>
<input id="abc" />
```
`input#abc` has no information itself, but we can infer a "Search" label.
