### ISSUE TITLE
Browser won't load

### ISSUE THREAD

**Issue by FeralSmurf** [lavague-ai/LaVague#35]
The browser simply won't load. Tried different urls, but still no joy.

![image](https://github.com/lavague-ai/LaVague/assets/111461128/714a0b2f-3d5b-4150-82c3-38523cabbefe)

**Comment by dhuynh95** [comment]
Did you click on Enter?

**Comment by lyie28** [comment]
It looks like this until you click on the URL and click enter @FeralSmurf ?

**Comment by FeralSmurf** [comment]
Yup, tried with ENTER in the url tab:

![image](https://github.com/lavague-ai/LaVague/assets/111461128/1f6336f8-6e6f-4f59-9f2f-36336e92de45)

**Comment by FeralSmurf** [comment]
> Connection refused for me: ![image](https://private-user-images.githubusercontent.com/7482112/313766272-b3c579e3-b386-4d45-a645-d6ce46803139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzkzOTQsIm5iZiI6MTcxMDgzOTA5NCwicGF0aCI6Ii83NDgyMTEyLzMxMzc2NjI3Mi1iM2M1NzllMy1iMzg2LTRkNDUtYTY0NS1kNmNlNDY4MDMxMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDkwNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M0ZjFjZjcwMmFjMGNmOTI2OGQwMzIyMmI2OGY4OGU1MTcyZjFkY2YyYWIyNjczNzczOWJhMDQwMDViOGZmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lQBzjZJWA0yHJj7opODd9-LYRtZNbhvyX-rYGq_XCbk)
> 
> How to proceed?

Same result here.

**Comment by FeralSmurf** [comment]
> It looks like this until you click on the URL and click enter @FeralSmurf ?

Thank you. Read the instructions a bit more carefully, this time :). However, I still get a connection refused error.

**Comment by FeralSmurf** [comment]
This is what I get when trying the default commands (select command --> ENTER):

![image](https://github.com/lavague-ai/LaVague/assets/111461128/544213c4-4da6-4638-ba52-4d9a9dd789e4)

(using goolge-chrome as the browser, on Arch).

**Comment by lyie28** [comment]
Hello again @FeralSmurf + @smilinrobin,

We have just released a first version of our CommandCenter module (wraps around all the Gradio and Selenium set-up code), updated our main notebook and released Python scripts for running LaVague using the HuggingFace API, OpenAI or a local model.

Can you let me know if your issues are solved by our updates please.

**Comment by smilinrobin** [comment]
Resolves my issue. Thanks.
