### ISSUE TITLE
LaVague fails to access and interact with iframe content

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#362]
### Description

LaVague cannot interact with content inside iframes. 

When we compare the output of `get_html()` in the `get_obs()` function in `base_driver.py` with the actual page content, it is clear that LaVague lacks access to iframe content.

LaVague should be able to interact with all elements in the DOM, including iframes and nested iframes, once the page has fully loaded.

### Steps to Reproduce

1. Visit `https://selectorshub.com/iframe-scenario/` where you will see three nested iframes.
2. Launch LaVague with an objective to fill the three input fields, such as "Enter foobar in the three inputs."
3. Observe LaVague's repeated attempts and failures to select these fields.

### Attachments

- Text output of the run with a `print(html)` in `get_obs()`
[test_iframe.txt](https://github.com/user-attachments/files/15883950/test_iframe.txt)

**Comment by mbrunel** [comment]
and shadow-dom if possible
