### ISSUE TITLE
Add option to Evaluator.compare method so we can optionally select to visualize just 1 or 2 elements of recall, precision & time

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#369]
By default, the Evaluator.compare method will provide visualization for the compared performance of recall, precision and time taken:

```
df = pd.DataFrame()
df["precision"] = [df["precision_retriever"].mean() for df in results.values()]
df["recall"] = [df["recall_retriever"].mean() for df in results.values()]
df["time"] = [df["retrieval_time"].mean() for df in results.values()]
df["name"] = list(results.keys())

```

I would like to add an optional list, where uses call supply any number of these measures so we are not obliged to see all three. For example:

```
retriever_evaluator.compare(metrics = ["recall", "precision"], results = {"default": default_ret, "my_custom_retriever": custom_ret})```

This will involve:
- adding optional list argument to compare method
- If this argument is set, adding only the relevant columns to the `df` variable.

**Comment by jashuajoy** [comment]
Hi @lyie28, I'm trying to implement this. Pls let me know if my understanding is correct:

- Users should have the ability to pass in a list of metrics as argument and the compare function should only show those metrics in the figure.
- The new argument must be an optional.
- If this argument is set, adding only the relevant columns to the `df` variable.

**Comment by lyie28** [comment]
Exactly. It is just so users have the option to have a graph for say just recall or just precision. The name column must always be included though.

We can do this for the compare methods for both the RetrieverEvaluator and LLMEvaluator :)

**Comment by jashuajoy** [comment]
ok, I will implement this.

**Comment by jashuajoy** [comment]
Hi @lyie28, I have created a pull request.
