### ISSUE TITLE
Local DB integration for logs

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#376]
Current we have an `AgentLogger` which stores a log of info for the last agent run in memory which can be retrieved with the `agent.logging.return_pandas()` method.

We also have a `LocalLogger` option that stores the log for the last run in a local file.

We would like to add an integration where you can set an option when using `agent.run()` to add the info from the logger info a local database with SQLlite. I had in mind something like this, but open to ideas:
`agent.run(objective=objective, url=url, log_to_db=True)`

More details about the logger is available in the docs:
https://docs.lavague.ai/en/latest/docs/learn/local-log/

Or in the logger.py file: https://github.com/lavague-ai/LaVague/blob/main/lavague-core/lavague/core/logger.py

**Comment by jashuajoy** [comment]
Hi @lyie28, I might be able to help you with this. 
A quick question: Should the local DB store all the log data(like the data being returned when agent.logging.return_pandas() is run)?

**Comment by lyie28** [comment]
Good question. @adeprez @dhuynh95 I had assumed we would pass all the log data to the database - is there anything you think we should drop?

**Comment by adeprez** [comment]
I support passing all the logs to the database, if any data needs to be filtered out, it should be removed before being collected in the logs

**Comment by lyie28** [comment]
Do you still want to work on this one @jashuajoy? Shall I assign it to you?

**Comment by jashuajoy** [comment]
Yes @lyie28. I have a few follow up questions. Will ping you in discord.

**Comment by lyie28** [comment]
Merged to main with #401 :)
