### ISSUE TITLE
Lavague gets stuck in endless loops for an action

### ISSUE THREAD

**Issue by smilinrobin** [lavague-ai/LaVague#393]
**Describe the bug**
When we use the [Getting started Colab notebook](https://colab.research.google.com/github/lavague-ai/lavague/blob/main/docs/docs/get-started/quick-tour-notebook/quick-tour.ipynb#scrollTo=1h8N8HCD6x_7), and run the Gradio demo, then Lavague goes in endless loops for clicks. 

**To Reproduce**
1. Run the Colab notebook
2. Run the below cell : `
```
driver = SeleniumDriver(headless=True, no_load_strategy=True)
action_engine = ActionEngine(driver)
world_model = WorldModel()
agent = WebAgent(world_model, action_engine)
agent.get("https://huggingface.co/docs")
agent.demo("")`
```

3. In the Gradio notebook, enter "Click on the Models link"
**Expected behavior**
Models link should be clicked ONLY ONCE. Here Lavague goes in endless of trying to click it thrice and more. 

**Screenshots**
![image](https://github.com/lavague-ai/LaVague/assets/7482112/449ec6ac-9bee-4de4-a7fb-f7c586130b20)

**Comment by dhuynh95** [comment]
I think it might be because it has difficulty understanding it finished the task. Maybe we should add the URL as the list of observed data to provide higher signal about where it landed

**Comment by smilinrobin** [comment]
Yes, we should update the Action engine and capture the URL, so that it doesn't go into a "hallucination" well.

**Comment by lyie28** [comment]
@dhuynh95 - I think we already have the URL in the observed data?

```python
obs = {
            "html": html,
            "screenshots_path": str(current_screenshot_folder),
            "url": url,
            "date": datetime.now().isoformat(),
        }
```

**Comment by lyie28** [comment]
This is now fixed so I will close this @smilinrobin - thanks for flagging this

![image](https://github.com/user-attachments/assets/b68fd80a-37e1-4489-a81b-13a9b04a45e3)
