### ISSUE TITLE
Ability to Control Execution Time of Instructions

### ISSUE THREAD

**Issue by Pranshu172** [lavague-ai/LaVague#395]
Is there a way to control the amount of time an agent takes to execute or perform an instruction in LaVague? Any guidance or suggestions on how to achieve this would be appreciated.

**Comment by dhuynh95** [comment]
Hi there!
It would be hard to bound it as it depends on the task at hand (and also on the AI provider if you use APIs like OpenAI).
However we are working on reducing time and cost by optimizing the retriever and prompt size!

**Comment by Pranshu172** [comment]
Okay 
Thank you.
