### ISSUE TITLE
Running qa_automation.py with ollama gets stucked

### ISSUE THREAD

**Issue by alexsiu398** [lavague-ai/LaVague#396]
**Describe the bug**

**To Reproduce**
modified qa_automation.py with ollama model
    llm = Ollama(model="deepseek-coder-v2:16b",request_timeout=120.0)
    embedding = OllamaEmbedding(
            model_name="llama3:instruct",
            base_url="http://localhost:11434",
            ollama_additional_kwargs={"mirostat": 0},
            )
    mm_llm = OllamaMultiModal(model="llava:13b")
client = OpenAI(
    base_url = 'http://localhost:11434/v1',
    api_key='ollama', # required, but unused
    )
    completion = client.chat.completions.create(
        model="deepseek-coder-v2:16b",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": [{"type": "text", "text": combined_prompt}]},
        ],
    )

Run qa_automation.py with --url https://www.saucedemo.com/v1/ --feature /LaVague-main/examples/qa-automation/tests/test_login.feature
It outputs the following:
"""
- The current screenshot shows the login page of Swag Labs.
- The objective is to run a test case where the user enters specific credentials and clicks on the login button to see if they are redirected to the home page and can view the product inventory.
- Since there is no information provided about what happens after the login, it's essential to use an engine that can perform such actions.
- The best next step is to use a Python Engine or Navigation Controls with instructions to simulate user input for testing purposes.
Next engine: Python Engine
Instruction: Use the Python Engine to simulate a login by entering "standard\_user" as the username and "secret\_sauce" as the password, then click on the login button, and finally check if the expected behavior of being redirected to the home page and seeing the product inventory is achieved.
"""

At the beginning, there was gpu usage and web browser was shown. But after a few minutes, it stucked and no gpu usage anymore. Is it possible it was caused by ollama or multi-modal llm?

**Expected behavior**
Perform test automation on webapp

**Comment by Richardson143** [comment]
Hi @alexsiu398 were you able to fix it?

**Comment by dhuynh95** [comment]
That's weird.

I am not sure it's due to us but maybe more to ollama. Our framework works well on our side with other MM LLM but I can try to have a look

**Comment by alexsiu398** [comment]
I am suspecting since I set up llm, embedding, mm_llm to ollama, my desktop may use three local models at the same time. Not having enough memory may cause the error.

**Comment by masterchop** [comment]
Could you please provide example with Ollama? i am sad to see every single framework is openai nothing is really for the local LLM's. Thanks

**Comment by dhuynh95** [comment]
@masterchop : unfortunately in the current pipeline we haven't found a way to make local models consistently good enough to allow for purely local models.

We do want to support it, and tried doing it, but it goes beyond our capabilities to develop a working local model for Web Agents.

For instance, open-source multimodal LLMs are not good enough to be used as world models. https://github.com/lavague-ai/LaVague/issues/272
Also, even for the navigation engine, they often have limited context window and are worse than proprietary solutions 

@paulpalmieri : could you put in the docs more clearly that we have tried supporting local models but no viable solution has emerged yet?

**Comment by paulpalmieri** [comment]
@dhuynh95 ok if I put it pretty high up in the customization guide ? https://docs.lavague.ai/en/latest/docs/get-started/customization/

We could have like a "LaVague recommends" section talking about our findings and recommend to run remote models rathers than local models for performance ?

**Comment by dhuynh95** [comment]
I think a quick mention in the quick tour / README, like in an alert box that says we tried but it does not work should be good. 

We can then point to a more lengthy description in the customization section. 

I think the spirit is that important stuff is mentioned in the README / Quick tour or Homepage and we point to more detailed explanations in the right parts of the docs
