### ISSUE TITLE
Not making use of embedding 

### ISSUE THREAD

**Issue by Indirajith-jithu** [lavague-ai/LaVague#405]
The BM25Retriever is used for finding the top k DOM elements which doesn't utilizing embeddings; however, The indexing process incorporates embeddings

[https://github.com/lavague-ai/LaVague/blob/5862028ebcadaa26269e07af2e530358e02a91cf/lavague-core/lavague/core/retrievers.py#L228](https://github.com/lavague-ai/LaVague/blob/5862028ebcadaa26269e07af2e530358e02a91cf/lavague-core/lavague/core/retrievers.py#L228)

**Comment by lyie28** [comment]
Hi @Indirajith-jithu,

Thanks for this.

So just to check, your point is that a BM25Retriever is incompatible with an index using embeddings?

Let me bring in our AI team @dhuynh95 @HiImMadness

**Comment by Indirajith-jithu** [comment]
Yes 

[https://github.com/run-llama/llama_index/blob/589b3054e22535fc7a43baa2bbd52aacc439b4f7/llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py#L82](https://github.com/run-llama/llama_index/blob/589b3054e22535fc7a43baa2bbd52aacc439b4f7/llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py#L82)
