### ISSUE TITLE
Navigation seems to be failing for simple google search style queries.

### ISSUE THREAD

**Issue by torque59** [lavague-ai/LaVague#411]
**Describe the bug**
Navigation seems to be failing for simple google search style queries. 

Note: i did not spend time debugging whether the xpath returned was accurate on this.

**To Reproduce**

See sample script used from readme example (slightly modified).

```
import os
from lavague.core import  WorldModel, ActionEngine
from lavague.core.agents import WebAgent
from lavague.drivers.selenium import SeleniumDriver

os.environ['TELEMETRY_VAR'] = "NONE"
os.environ["LAVAGUE_TELEMETRY"] = "NONE"

selenium_driver = SeleniumDriver(headless=False)
world_model = WorldModel()
action_engine = ActionEngine(selenium_driver)
agent = WebAgent(world_model, action_engine)
agent.get("https://google.com")
agent.run("find me the rick roll youtube video and play it.")

```
Lavague versions installed/used:

```
pip freeze | grep lavague

lavague==1.1.6
lavague-contexts-openai==0.2.0
lavague-core==0.2.20
lavague-drivers-selenium==0.2.7
lavague-gradio==0.2.4


```

**Expected behavior**
The expected behavior is to execute the search on google and find the youtube video.

**Screenshots**
![Screenshot 2024-07-05 at 9 31 01 AM](https://github.com/lavague-ai/LaVague/assets/6204290/5b89ea9d-b6ff-4676-976e-b397e6e8e85b)

**Comment by dhuynh95** [comment]
Google is a tough one as they are making it hard to automate but we managed to find ways to have consistent results. @adeprez has something solid coming out soon. We will keep you updated on progress

**Comment by dhuynh95** [comment]
You can have a glimpse here https://github.com/lavague-ai/LaVague/tree/feat/dom-interactive-navigation
