### ISSUE TITLE
Estimate run cost

### ISSUE THREAD

**Issue by adeprez** [lavague-ai/LaVague#428]
#415 introduces a method to count tokens. We would like to extend this functionality to estimate the cost of a run based on the token count. The pricing model should be configurable to accommodate different rates for different token types or services.

**Comment by jashuajoy** [comment]
Hi @adeprez, currently there is no API endpoint for openai token pricing. One has to do it manually. If it is ok, I can implement this functionality. Pricing data needs to be updated manually in a separate file (json or yaml).

**Comment by adeprez** [comment]
Hi, it would be great if you want to help with this! An estimation using a formula / config file sounds like a good idea.

**Comment by jashuajoy** [comment]
Hi @adeprez, opened a pr #430. Pls check it out.

**Comment by adeprez** [comment]
Thank you for your contribution! Your changes have been merged
