### ISSUE TITLE
Add documentation for latest features

### ISSUE THREAD

**Issue by adeprez** [lavague-ai/LaVague#433]
- [x] Document SQLite logs usage
- [x] Document token count feature
- [x] Document cost estimation feature
- [x] Create a matrix of supported features per driver
- [x] WebAgent#run(step_by_step=True) and WebAgent#run_step methods to debug single step
- [x] Selenium driver tool to highlight elements

**Comment by paulpalmieri** [comment]
A few notes: 
- SQLite docs is ready, waiting for PR merge to fix a bug before
- Token count and cost seems broken: https://github.com/run-llama/llama_index/issues/13146 we get weird results like 0 embedding_tokens and 0.11 llm_completitions_token

**Comment by dhuynh95** [comment]
@paulpalmieri we no longer use embeddings for the retriever for Navigation, we do use it if we search for information with the current text of the page.
The LLM completion tokens being 0.11 is an issue though

**Comment by paulpalmieri** [comment]
llm_completions_token issue fixed by #439

**Comment by paulpalmieri** [comment]
For documenting the new debug features. 
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/fa087b67-1785-4efd-a28c-f6be05104c1b">

https://github.com/lavague-ai/LaVague/pull/443

**Comment by timreddick-8451** [comment]
@paulpalmieri

![image](https://github.com/user-attachments/assets/56fbd151-5d58-4b24-94b6-fe28497ded9f)
![image](https://github.com/user-attachments/assets/9a9b2ac9-d5eb-42d7-b022-d268cdb269ce)

I'm running lavague-core. Seems there is no step-by-step keyword when initializing WebAgent?

**Comment by lyie28** [comment]
Hi @timreddick-8451, thanks for flagging this. The step_by_step option is actually part of the agent.run() method not the agent constructor. I will update the docs now.

**Comment by timreddick-8451** [comment]
Thanks! One more point of clarification. Is agent.run_step() equivalent then to agent.run(step_by_step=True)?

**Comment by timreddick-8451** [comment]
@lyie28

I can take this to a new issue or the support channel on discord, but any obvious reason why I'm seeing this when trying to call `agent.run_step()`: `AttributeError: 'AgentLogger' object has no attribute 'current_row'`. This doesn't happen with `agent.run(step_by_step=True)`. I did have to custom define my models to point to my org's model proxy:

```
def create_multi_modal_llm(api_key: str) -> OpenAIMultiModal:
    """Create and return the multi-modal LLM."""
    return OpenAIMultiModal(
        model="gpt-4o",
        api_base=API_BASE,
        api_key=api_key,
    )
```

I then pass my models into a Context, Agent, etc. I might have to do some custom configuration to the logger?
