### ISSUE TITLE
Time Until Production Ready

### ISSUE THREAD

**Issue by KartikeyBartwal** [lavague-ai/LaVague#455]
I wanted to ask regarding the stability of this framework. Is this stable enough to be used in production ? What are its future plans and objectives ? 
I would love to be a contributor in this repo, thank you

**Comment by paulpalmieri** [comment]
Hello, what kind of use cases do you have in mind ? Evaluating stability can be tricky and can depend a lot on what you're trying to accomplish. 

Don't hesitate to join our Discord if you haven't already :)

**Comment by KartikeyBartwal** [comment]
For sure, I will, thank you!
