### ISSUE TITLE
Improvements to `lavague-test`

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#462]
`lavague-tests` is a module to help us evaluate the behaviour of an agent on specific websites and use cases. 

Here's an example report after running `lavague-tests -s google.com`
```
[x] Go to LaVague.ai from https://google.com
    (x) URL is https://lavague.ai - was: https://www.google.com/
    (x) Status is success - was: failure

Result: 0 % (0 / 2)
```

What can be improved: 
- improve the modul to allow users to specify llm, mm_llm, embedding models
    - handled at the module level or at the site level ?
    - make sure token counting works properly

- improve the report to display: 
    - which models were used
    - tokens consumed
    - estimated costs (note that this only works for models supported by llama-index and that pricing info has to be in `pricing_config.yaml`

**Comment by adeprez** [comment]
> improve the modul to allow users to specify llm, mm_llm, embedding models
> 
> handled at the module level or at the site level ?

I'd define precedence as follows:
- CLI Argument: Overrides all other settings.
- Site Level: Used if CLI argument is not provided.
- Module Level: Default fallback if neither of the above is set.

> improve the report to display:
>
> which models were used
> tokens consumed
> estimated costs (note that this only works for models supported by llama-index and that pricing info has to be in > pricing_config.yaml

In addition to display, token consumtion and price could be added as available properties so we can make test conditions out of it.

So far reports are made out of string concatenations, if you find a lib to generate test reports feel free to use it.
