### ISSUE TITLE
Waterfall chart to understand Agent bottleneck latency issues

### ISSUE THREAD

**Issue by dhuynh95** [lavague-ai/LaVague#469]
We provide logs in our agents through the `agent.logger` that can be used after each run but it can be hard to read the CSV we get from `agent.logger.return_pandas()`

Could be cool to have some waterfall graph like this 
![image](https://github.com/user-attachments/assets/6775d297-a2e0-4d80-9f09-07395546a564)

but instead we see the time it takes on each step, and the decomposition (World model, rephrase, retriever, LLM, etc.).

Maybe we could have something like `agent.logger.plot()` to do that

**Comment by paulpalmieri** [comment]
@dhuynh95 agent-ops does that https://docs.agentops.ai/v1/usage/dashboard-info

**Comment by lyie28** [comment]
@jashuajoy What do you think of this idea? Would you be interested in working on this since you know our logger system pretty well :)

**Comment by jashuajoy** [comment]
@lyie28 I can implement that.

**Comment by paulpalmieri** [comment]
@jashuajoy I'll take this issue as we are prioritising observability at the moment.

**Comment by paulpalmieri** [comment]
@adeprez @dhuynh95 agent-ops provides waterfall chats out of the box. It's free for 1,000 events per month. 

What do you want in terms of UX ? 

We could attempt to activate it by default if an agentops API key is detected in the env ? This way we don't add yet another parameter to the agent.

Or it could be an argument passed to the agent (either the key or a flag). 

Here's an example: 

![image](https://github.com/user-attachments/assets/9ea4b344-62ae-4588-bc8a-a09613f381e0)

**Comment by paulpalmieri** [comment]
We could start with something simple like: https://github.com/lavague-ai/LaVague/commit/f265f2a3ea21d4199d5e140dc0355d24c0c41981

Usage: 
1. Create an account on agentops and get a key
2. Setup `AGENTOPS_KEY` as an envrionement variable (don't forget to `source` your shell config after)
```
export AGENTOPS_KEY=<yourkey>
```
3. Enable it for a given run if needed
```
output = agent.run("your objective", agent_ops=True)
```

**Comment by adeprez** [comment]
Is AgentOps capable of detecting which methods take more time, or do we need to decorate the methods? On the example I can see LLM calls, but we want to monitor regular python code too (driver calls, algorithms, ...). It can be a good start - but some might reach the 1k limit quite fast.

Creating a custom timing decorator to store it inside the logs dataframe might be a good option. This way, it could be analyzed with any waterfall chart library without having to rely on 3rd party service. And we could use telemetry to track performance
