### ISSUE TITLE
Feature suggestion: Add LAVAGUE_LOG_TO_DB environment variable for automatic logging to db without need for option

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#474]
@adeprez @jashuajoy @mbrunel Maybe it is a bit annoying to have to set log_to_db to true each time if you always want to log to DB, so what would you think of adding an environment variable or config file in a default location or something like this where we can set it to true permanently if we like?

**Comment by jashuajoy** [comment]
@lyie28 Good idea, will implement this.

**Comment by paulpalmieri** [comment]
@jashuajoy FYI I've made a few changes to the DB log logic following your initial implementation: https://github.com/lavague-ai/LaVague/commit/772357f4f3dcb28969f3edd3252974de418f1722

**Comment by jashuajoy** [comment]
@lyie28 opened pull request #486

**Comment by paulpalmieri** [comment]
What about keeping the argument in `Agent.run()` ? 
Would could check the presence of the argument and if it's not here, look at the env variable.

Sometimes I want to turn on/off logging momentarily and having to change an env variable would be cumbersome.

Also we might need to check the docs if we go though with the change as it is.

What do you think @lyie28 @jashuajoy ?

**Comment by jashuajoy** [comment]
@paulpalmieri it makes more sense based on your input to keep the argument. So, will add it back.

So, if the argument is true then we don't need to check the env var and if false then env var needs to be checked to insert logs to db. Is my conclusion right?

**Comment by paulpalmieri** [comment]
Yeah, you should be able to do it like this: 
Make sure you keep the argument `log_to_db` with default to `False` then this should work
```python
if log_to_db or os.getenv("LAVAGUE_LOG_TO_DB", "").lower() in ("true", "1", "y", "yes"):
    local_db_logger = LocalDBLogger()
    local_db_logger.insert_logs(self)
```
