### ISSUE TITLE
Add more detailed token consumption output to `lavague-tests`

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#487]
In order to do more detailed benchmarks and comparison, having more details than just the total number of consumed tokens would be helpful. 

Ideally a breakdown by input/output tokens with the type of llms, show the name of the models used as well. 

```
success rate (%)
input | output
llm
mm_llm
embedding
```

**Comment by lyie28** [comment]
Maybe we should also add time taken to this print out as well - I think it could be useful @paulpalmieri
