### ISSUE TITLE
Unable to run ActionEngine in Colab

### ISSUE THREAD

**Issue by 11PRiyansh** [lavague-ai/LaVague#51]
It gives a TypeError saying , 
Missing "Prompt" argument.

Kindly suggest what am I doing wrong.
![Screenshot 2024-03-21 163156](https://github.com/lavague-ai/LaVague/assets/160034930/95751134-75ca-45b1-bd0e-0999642f7cbf)

**Comment by lyie28** [comment]
There has been a few updates in the code + notebooks over the past day or so- please try again with the updated notebook and let me know if it works for you now :)

**Comment by dhuynh95** [comment]
Weird, let me have a look.

**Comment by dhuynh95** [comment]
Works on the latest Colab: https://colab.research.google.com/github/lavague-ai/LaVague/blob/main/docs/docs/get-started/quick-tour.ipynb?
