### ISSUE TITLE
Timeout error when using this project.

### ISSUE THREAD

**Issue by deepanshu-yadav** [lavague-ai/LaVague#58]
Hi,
First of all excellent work. I am facing issue with timeouts. I am able to install and run the demo. That's good. However when go the gradio app like this. 
I typed in https://youtube.com

<img width="644" alt="Screenshot 2024-03-22 151431" src="https://github.com/lavague-ai/LaVague/assets/13177663/431d0d0f-ab69-4b45-9831-745afd4f7062">

Then I supplied the following query
<img width="711" alt="Screenshot 2024-03-22 151443" src="https://github.com/lavague-ai/LaVague/assets/13177663/3573dfa3-f831-4214-b43b-2ddabf7ad9e9">

It went on to execute this statement forever. Moreover it does not display any errors or stack trace.   

<img width="711" alt="Screenshot 2024-03-22 151529" src="https://github.com/lavague-ai/LaVague/assets/13177663/da56e788-1959-4cc6-953d-1869ed398b64">

**Comment by dhuynh95** [comment]
I think websites like YouTube have pretty complex anti scrapping capabilities which explain this

Have you tried it on less technologically advanced websites?

**Comment by lyie28** [comment]
Closing as haven't had a reply for a while

**Comment by deepanshu-yadav** [comment]
Its because the project is **it.
