### ISSUE TITLE
extract_xpaths_from_html not reflected in most recent lavague-core==0.2.35

### ISSUE THREAD

**Issue by rtreddick** [lavague-ai/LaVague#599]
@lyie28, I'm following the Navigation engine docs here: https://docs.lavague.ai/en/latest/docs/module-guides/navigation-engine/

```
context = "\n".join(nodes)
action = nav_engine.get_action_from_context(context, instruction)
display(Code(action, language="python"))
```

When I run this code in my notebook, I get "KeyError: 'authorized_xpaths'". I'm running lavague-core==0.2.35 and lavague 1.1.19.

I see some changes were made last week to NavigationEngine: https://github.com/lavague-ai/LaVague/blame/b343013e67e965a579c4c415083a5e771dbf6d00/lavague-core/lavague/core/navigation.py#L177

It seems like I'm in a state where the NAVIGATION_ENGINE_PROMPT_TEMPLATE has been updated to include authorized_xpaths, but the `get_action_from_context method` changes are not reflected in most recent version of lavague-core.

**Comment by lyie28** [comment]
Hi @rtreddick - thanks for this. You're absolutely right. Unfortunately, a few things haven't been updated on the docs as we've been focusing on some other changes at the moment - I'll fix this one now.  Do let us know if you have any other issues or feel free to directly open a PR if you want to suggest a change directly :)

**Comment by lyie28** [comment]
Hi @rtreddick - thanks for this. I checked and we don't have the issue when installing from local but I see the issue if I download from the pypi package so I will find the package that needs updated and publish the latest version

**Comment by rtreddick** [comment]
That’s what I was thinking. Just the package on PyPi wasn’t up to date.
