### ISSUE TITLE
When can Playwright support headless mode? Is there a time plan ？

### ISSUE THREAD

**Issue by xiao56339207** [lavague-ai/LaVague#616]
I want to get an idea of the schedule

**Comment by lyie28** [comment]
Hi @xiao56339207, this should already work if you install the lavague-playwright-driver package and set the headless option to 'True' when initializing the driver. For example:

```
from lavague.contexts.openai import OpenaiContext
from lavague.drivers.playwright import PlaywrightDriver
from lavague.core import ActionEngine, WorldModel
from lavague.core.agents import WebAgent

# Set up our three key components: Driver, Action Engine, World Model
driver = PlaywrightDriver(headless=True)
action_engine = ActionEngine(driver=driver)
world_model = WorldModel()

# Create Web Agent
agent = WebAgent(world_model, action_engine)

# Set URL
agent.get("https://huggingface.co/docs")

# Run agent with a specific objective
agent.run("What is the name of the top trending dataset?")
```

**Comment by xiao56339207** [comment]
I'm using lavague version 1.1.19  as pip install lavague. But I don't see driver of playwright in this code base, I don't know why.

My environment is macOS, python 3.10

<img width="552" alt="image" src="https://github.com/user-attachments/assets/4184fd05-8dce-4e47-9667-962b937c71f7">

**Comment by lyie28** [comment]
It's normal - it's an optional dependency - it doesn't get installed from 'pip install lavague'. You can run 'pip install lavague-drivers-playwright'

**Comment by xiao56339207** [comment]
Thank you. I can use it now！
