### ISSUE TITLE
Split dependencies to install

### ISSUE THREAD

**Issue by dhuynh95** [lavague-ai/LaVague#62]
We have a monolithic installation process, for instance cuda is installed by default, which is too heavy for some use cases.

We will provide soon a version where the Action Engine can be provided through a SaaS to make it easier for people who don't want to do computing locally, so their package will be very lightweight.

@lyie28 Could you have a look? I guess this can be done in conjunction with #59

**Comment by lyie28** [comment]
Closing as duplicate issue
