### ISSUE TITLE
Create browser extension inspired by parts of Selenium IDE

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#7]
-> Specs: doesn't require developer mode

**Comment by retsamcam** [comment]
This would be interesting

**Comment by shivamsharma00** [comment]
I would like to work on this issue.

**Comment by lyie28** [comment]
@dhuynh95 @mbrunel

**Comment by lyie28** [comment]
@shivamsharma00 That would be awesome! Are you on our Discord server? It would be great to schedule a quick call to discuss this with you

**Comment by shivamsharma00** [comment]
> r

Hey @lyie28 I am on discord server, my username is "galeetch". Let us schedule a quick call to discuss this.
