### ISSUE TITLE
Add support for Hugging face inference with docker image

### ISSUE THREAD

**Issue by shyampatadia** [lavague-ai/LaVague#84]
**Is your feature request related to a problem? Please describe.**

Currently the docker has only 2 commands, build and launch, and it launches the config.py file, what If I want to use huggingface_interface.py?

Can we modify the entrypoint.sh? and add the support for huggingface and possibly for others?

 
**Describe the solution you'd like**
Modifying the entrypoint.sh file and adding the support for the same.

**Describe alternatives you've considered**
I am not sure about the alternatives, but modifying the entrypoint.sh seems a good solution at this point.

**Additional context**

**Comment by lyie28** [comment]
Hey @shyampatadia, a couple of things here:

1) You can actually replace the build or run with any custom command you like - they are just shortcuts. So you could instead have lavague-launch --file_path new-instructrions.txt --config_path new-config.py - just make sure these files are in your lavague-files mounted volume

2) In any case, no need to change the command, it will build launch with whatever config is in the config.py in the lavague-files mounted volume. You just need to copy the HuggingFace one we provide in the examples/api folder into this file. Then swap the -e option in the docker run command to HF_TOKEN=[your token] - you can also modify the instructions.txt file if you want to change instructions

**Comment by shyampatadia** [comment]
Oh okay okay got it, my bad, really sorry, there is already a custom command available in entrypoint.sh

previously I was trying the docker command without lavague prefix, below is the fixed command:

`docker run -v PATH\LaVague\lavague-files:/home/vscode/lavague-files -e HF_TOKEN=VALUE -p 7860:7860 lavagueai/lavague:latest lavague-launch --file_path=instructions.txt --config_path=huggingface_inference.py`

It works now, hence closing the issue.
