### ISSUE TITLE
Add compatibility for behave input for instructions

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#89]
Behave:
- https://behave.readthedocs.io/en/latest/philosophy/
- https://behave.readthedocs.io/en/latest/tutorial/

Behave is a behavior-driven development (BDD) framework which uses Gherkin language for writting automation scenarios, for example:

```
Feature: Automated web interaction
  Scenario: Login to the website
    Given a user navigates to the login page
    When the user enters valid credentials
    Then the user should be redirected to the dashboard
```

We would like to be able to optionally handle Behave scenario files as an instruction input and output the necessary code to perform these actions.

**Comment by slimwizard** [comment]
Hi @lyie28, could you provide another example or two of what you have in mind for the kind of content which would be in a Behavior file that would be used with LaVague?
