### ISSUE TITLE
Unable to run lavague-launch/lavague build locally

### ISSUE THREAD

**Issue by 11PRiyansh** [lavague-ai/LaVague#91]
After the two installation steps, it gives error when running lavague-build/launch saying command not found.
Please guide.

**Comment by lyie28** [comment]
Hi @11PRiyansh, please share your error message

**Comment by lyie28** [comment]
For local installation, the setup.sh script does the following:

```
# Install LaVague from main of GitHub repo
git clone https://github.com/lavague-ai/LaVague.git
pip install -e LaVague
```

Can you confirm you have the gh repo locally and try repeating the pip install step and check if it was installed?

**Comment by 11PRiyansh** [comment]
Thank you for the prompt reply.
My problem is with running the lavague-build. 
After some debugging I was able to solve the issue but now it gives me 

cmd:: 
lavague-build --file_path tests/hf.txt --config_file examples/api/huggingface_infe
rence.py
Output:: 
usage: lavague-build [-h] --file_path FILE_PATH --config_path CONFIG_PATH
lavague-build: error: the following arguments are required: --config_path

Also, which script should I be running to get the Gradio live url/link.

Thank you.

**Comment by lyie28** [comment]
Ah, so your problem is just that you put --config_file instead of --config_path :)

The Gradio is with the lavague-launch command. If When it finishes running you should see the pink in the standout output from the command, you can just click it either the public or local URL and it will open in the browser

**Comment by 11PRiyansh** [comment]
Thank you ! It worked.
